name = "SQLite"
uuid = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "1.1.4"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SQLite_jll = "76ed43ae-9a5d-5a62-8c75-30186b810ce8"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[compat]
BinaryProvider = "0.5"
DBInterface = "2.4"
SQLite_jll = "3"
Tables = "1"
WeakRefStrings = "0.4,0.5,0.6"
julia = "1"
