name = "SQLite"
uuid = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>", "JuliaData Contributors"]
version = "1.4.1"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SQLite_jll = "76ed43ae-9a5d-5a62-8c75-30186b810ce8"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[compat]
DBInterface = "2.5"
SQLite_jll = "3"
Tables = "1"
WeakRefStrings = "0.4,0.5,0.6,1"
julia = "1.3"
