name = "SQLite"
uuid = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "0.9"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[compat]
BinaryProvider = "0.5"
DataFrames = "0.18,0.19,0.20"
Tables = "0.1,0.2"
WeakRefStrings = "0.4,0.5,0.6"
julia = "1"
